version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: assistant
    volumes:
      - ./src:/code
    env_file:
      - variables.env
    ports:
      - "8080:8080"
